uploads = []

[[generated]]
id = "1tetPNn0xk6HjIhn_FToL"
uri = "file://artifacts/tixinshijie-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "0aPMetG4Rb0DcBOhQfd7S"
uri = "file://attached_assets/facebook-qrcode.png"
type = "image"
title = "Facebook QR Code（含 F 圖示）"

[[outputs]]
id = "yuXKmZXFnpB7s8dUBsOa1"
uri = "file://artifacts/tixinshijie/public/tixinshijie-qrcode.png"
type = "image"
title = "貼心世界.com QR Code"
