const colors = {
  light: {
    text: "#ffffff",
    tint: "#00d4ff",
    background: "#07070f",
    foreground: "#ffffff",
    card: "#0d1220",
    cardForeground: "#ffffff",
    primary: "#00d4ff",
    primaryForeground: "#07070f",
    secondary: "#0080ff",
    secondaryForeground: "#ffffff",
    muted: "#161c2e",
    mutedForeground: "#a0aec0",
    accent: "#7c3aed",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e2a4a",
    input: "#1e2a4a",
  },
  dark: {
    text: "#ffffff",
    tint: "#00d4ff",
    background: "#07070f",
    foreground: "#ffffff",
    card: "#0d1220",
    cardForeground: "#ffffff",
    primary: "#00d4ff",
    primaryForeground: "#07070f",
    secondary: "#0080ff",
    secondaryForeground: "#ffffff",
    muted: "#161c2e",
    mutedForeground: "#a0aec0",
    accent: "#7c3aed",
    accentForeground: "#ffffff",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1e2a4a",
    input: "#1e2a4a",
  },
  radius: 12,
};

export default colors;
